config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :acceptables

  devise_for :users, :controllers => { :sessions => "sessions", :registrations => "registrations" }

  resources :guild_memberships

  resources :messages, :except => [ :index, :show ] do
    member do
      patch     :undelete
      delete  :purge
      get     :move
      patch     :save_move
    end
  end

  resources :boards do
    member do
      patch :move_up
      patch :move_down
      patch :switch_open_or_closed
    end

    collection do
      get :admin
      get :mark_read
    end
  end

  resources :transactions, except: [:destroy]
  resources :campaigns

  resources :games do
    member do
      get :edit_ic_brief
      get :edit_ooc_brief
      get :edit_ic_debrief
      get :edit_ooc_debrief
      patch :update_ic_brief
      patch :update_ooc_brief
      patch :update_ic_debrief
      patch :update_ooc_debrief
      get :start_debrief
      patch :confirm_start_debrief
      patch :finish_debrief
      patch :reopen_debrief
      patch :publish_briefs
      get :first_aid_report
    end

    collection do
      get :outstanding_debriefs
    end

    resources :game_attendances, :except => [ :index, :show, :destroy ] do
      member do
        patch :clear_confirm_state
        patch :confirm
        patch :prioritise
        patch :reject
      end
    end

    resources :game_applications, :except => [ :show ] do
      member do
        get :approve_app
        get :reject_app
        patch :approve
        patch :reject
      end
    end

    resources :debriefs, :except => [ :show, :new, :edit, :index ] do
      new do
        get :new_gm
        get :new_player
        get :new_monster
      end

      member do
        get :edit_gm
        get :edit_player
        get :edit_monster
      end
    end

    resources :users, :except => [ :new, :create, :show, :edit, :update, :index, :destroy ] do
      new do
        get :new_gm
        get :new_player
        get :new_monster
        patch :create_gm
        patch :create_player
        patch :create_monster
      end

      resources :characters, :except => [ :new, :create, :show, :edit, :update, :index, :destroy ] do
        new do
          get :new_player
          patch :create_player
        end
      end
    end

    resource :gm_contact, :except => [ :show, :edit, :update, :index, :destroy ]

  end

  resources :characters do
    collection do
      get :show_all
    end

    member do
      get :edit_name
      get :edit_bio
      get :edit_date_of_birth
      get :edit_notes
      get :edit_player_notes
      get :edit_gm_notes
      get :edit_address
      patch :update_name
      patch :update_bio
      patch :update_date_of_birth
      patch :update_notes
      patch :update_player_notes
      patch :update_gm_notes
      patch :update_address
      patch :reactivate
      patch :retire
      patch :perm_kill
      patch :resurrect
      patch :approve
      patch :reject
      get :edit_rejected
      patch :update_rejected
      get :declare
      patch :save_declaration
      patch :recycle
    end

    resources :death_threshold_adjustments, :except => [ :index, :show, :destroy ] do
      member do
        patch :approve
        patch :reject
        patch :approve_from_approvals
        patch :reject_from_approvals
      end
    end
    resources :character_point_adjustments, :except => [ :index, :show, :destroy ] do
      member do
        patch :approve
        patch :reject
      end
    end

    resources :monster_point_spends, :except => [ :index, :show, :destroy, :edit, :update ] do
      new do
        delete :delete
      end
    end

    resources :guild_memberships, :except => [ :index, :show ] do
      new do
        post :leave
        post :eject
        post :eject_from_approvals
        get  :branch_change
        post :create_guild_branch_change
        post :make_full
        post :make_full_from_approvals
      end

      member do
        patch :approve
        patch :provisionally_approve
        patch :reject
        patch :approve_from_approvals
        patch :provisionally_approve_from_approvals
        patch :reject_from_approvals
      end
    end

    resources :transactions, :only => [ :new, :create, :destroy ] do
      new do
        get :new_to_character
      end
    end
  end

  resource :sidebar, :only => :edit do
    resources :sidebar_categories, :as => :categories do
      member do
        patch :move_up
        patch :move_down
      end
    end
    resources :sidebar_entries, :as => :entries do
      member do
        patch :move_up
        patch :move_down
      end
    end
  end

  resources :pages do
    member do
      get :home
    end
  end

  resources :users, :except => [ :edit, :update ] do
    collection do
      get  :merge_select_users
      post :merge_select_data
      post :merge
    end

    member do
      patch :suspend
      patch :unsuspend
      delete :purge
      patch :approve
      patch :undelete
      post :resend_activation
      get :monster_points
      get :edit_user_name
      patch :update_user_name
      get :edit_login
      patch :update_login
      get :edit_email
      patch :update_email
      get :edit_mobile_number
      patch :update_mobile_number
      get :edit_emergency_details
      patch :update_emergency_details
      get :edit_general_notes
      patch :update_general_notes
      patch :enable
      get :terms_and_conditions
      post :accept_terms_and_conditions
      post :reject_terms_and_conditions
      post :reject_terms_and_conditions_and_accept_suspension
    end

    resources :monster_point_adjustments, :except => [ :index, :show, :destroy ] do
      member do
        patch :approve
        patch :reject
        patch :approve_from_approvals
        patch :reject_from_approvals
      end
    end

    resource :monster_point_declaration, :except => [ :show, :destroy ] do
      member do
        patch :approve
        patch :reject
        patch :approve_from_approvals
        patch :reject_from_approvals
      end
    end

    resource  :account
    resources :roles, :only => [:index] do
      collection do
        post :update
      end
    end
  end

  resource :committee_contact, :except => [ :show, :edit, :update, :index, :destroy ]

  root :to => "pages#home"

  get "/event_calendar"   => "games#list_future",        :as => :event_calendar
  get "/past_games/:year" => "games#index",              :as => :past_games
  get "/next_game"        => "games#next_game",          :as => :next_game
  get "/my_characters"    => "characters#my_characters", :as => :my_characters
  get "/monster_points"   => "my_info#monster_points",   :as => :monster_points
  get "/approvals"        => "admin#approvals",          :as => :approvals
  get "/user_profile"     => "users#profile",            :as => :user_profile

  if Rails.env.production?
    get '404', :to => 'application#page_not_found'
    get '422', :to => 'application#server_error'
    get '500', :to => 'application#server_error'
  end
  
end

app/models/debrief.rb
class Debrief < ApplicationRecord
    belongs_to :game
    belongs_to :user
    belongs_to :character, optional: true
  
    validates_presence_of :game_id
    validates_presence_of :user_id
    
    validates_numericality_of :base_points, :only_integer => true, :greater_than_or_equal_to => 0, :allow_nil => true
    validates_numericality_of :points_modifier, :only_integer => true, :allow_nil => true
    validates_numericality_of :money_modifier, :only_integer => true, :allow_nil => true
    validates_numericality_of :loot, :only_integer => true, :allow_nil => true
    validates_numericality_of :deaths, :only_integer => true, :allow_nil => true
    validate :max_one_gm_or_monster_debrief, :max_one_player_debrief, :base_points_less_than_or_equal_to_game_base, :danger_pay_non_negative
    
    after_destroy :delete_gm, :if => :is_gm_debrief?
    
    attr_accessor :player_debrief
    
    accepts_nested_attributes_for :character
    
    auto_strip_attributes :remarks
    
    def points
        if character.nil?
            (base_points.nil? ? game.monster_points_base : base_points) + (points_modifier || 0)
        else
            (base_points.nil? ? game.player_points_base : base_points) + (points_modifier || 0)
        end
    end
    
    def money
        unless character.nil? or game.player_money_base.nil?
            game.player_money_base + (money_modifier || 0)
        end
    end
    
    def is_provisional?
        game.open
    end
    
    def is_player_debrief?
        !character.nil? || @player_debrief
    end
    
    def is_gm_debrief?
        game.gamesmasters.exists? user.id
    end
    
    protected
        def max_one_gm_or_monster_debrief
            unless is_player_debrief?
                errors.add(:user_id, "already has a GM or monster debrief for this game") if 
                    (game.gm_debriefs + game.monster_debriefs).any? {|debrief| debrief.user == user and debrief.id != id }
            end
        end
        
        def max_one_player_debrief
            if is_player_debrief?
                errors.add(:character_id, "already has a player debrief for this game") if
                    (game.player_debriefs).any? {|debrief| debrief.character == character and debrief.id != id }
            end
        end
        
        def base_points_less_than_or_equal_to_game_base
            unless base_points.nil?
                if character.nil?
                    errors.add(:base_points, "must be less than or equal to monster base for the game") if base_points > game.monster_points_base
                else
                    errors.add(:base_points, "must be less than or equal to player base for the game") if base_points > game.player_points_base
                end
            end
        end
        
        def delete_gm
            game.gamesmasters.delete(user)
        end
        
        def danger_pay_non_negative
            if is_player_debrief?
                if !money.nil? && (money < 0)
                    errors.add(:money_modifier, "cannot reduce danger pay below zero florins")
                end
            end
        end
end

app/controllers/debriefs_controller.rb
class DebriefsController < ApplicationController
    before_action :authenticate_user!
    before_action :find_game
    before_action :find_debrief, :except => [ :new_gm, :new_monster, :new_player, :create ]
    before_action :check_can_edit_game
    before_action :check_ajax
    before_action :check_game_not_closed

    def new_gm
        @debrief = @game.debriefs.build
        respond_to do |format|
            format.js { render :new_gm }
        end
    end

    def new_monster
        @debrief = @game.debriefs.build
        respond_to do |format|
            format.js { render :new_monster }
        end
    end

    def new_player
        @debrief = @game.debriefs.build
        @debrief.player_debrief = true
        respond_to do |format|
            format.js { render :new_player }
        end
    end

    def create
        debrief_type = params[:debrief_type]
        
        case
        when debrief_type == "GM" then 
          @debrief = @game.debriefs.build(debrief_monster_params)
          create_gm
        when debrief_type == "Monster" then 
          @debrief = @game.debriefs.build(debrief_monster_params)
          create_monster
        when debrief_type == "Player" then 
          @debrief = @game.debriefs.build(debrief_player_params)
          create_player
        else unknown_debrief_type
        end
    end

    def edit_gm
        respond_to do |format|
            format.js
        end
    end

    def edit_monster
        respond_to do |format|
            format.js
        end
    end
    
    def edit_player
        @debrief.player_debrief = true
        respond_to do |format|
            format.js
        end
    end

    def update
        debrief_type = params[:debrief_type]
        
        case
        when debrief_type == "GM" then update_gm
        when debrief_type == "Monster" then update_monster
        when debrief_type == "Player" then update_player
        else unknown_debrief_type
        end
    end

    def destroy
        @debrief.destroy
        update_game_display
    end

    protected
    
        def debrief_monster_params
            params.require(:debrief).permit(:game_id, :user_id, :base_points, :points_modifier, :remarks)
        end
        
        def debrief_player_params
            params.require(:debrief).permit(:game_id, :user_id, :character_id, :base_points, :points_modifier, :remarks, :money_modifier, :loot, :deaths, :character_attributes => [:id, :gm_notes])
        end
        
        def find_game
            @game = Game.find(params[:game_id])
        end
        
        def find_debrief
            @debrief = Debrief.find(params[:id])
        end
        
        def check_can_edit_game
            @game.is_editable_by? current_user
        end
        
        def check_game_not_closed
            !@game.is_debrief_finished?
        end
        
        def create_gm
            if params[:user_selected] == "true"
                if @debrief.save
                    @game.gamesmasters << @debrief.user
                    update_game_display
                else
                    @withname = true
                    respond_to do |format|
                        format.js { render :new_gm }
                    end
                end
            else
                if @debrief.valid?
                    @withname = true
                    respond_to do |format|
                        format.js { render :new_gm }
                    end
                else
                    @debrief.user_id = nil
                    @withname = false
                    respond_to do |format|
                        format.js { render :new_gm }
                    end
                end
            end
        end
        
        def create_monster
            if params[:user_selected] == "true"
                if @debrief.save
                    update_game_display
                else
                    @withname = true
                    respond_to do |format|
                        format.js { render :new_monster }
                    end
                end
            else
                if @debrief.valid?
                    @withname = true
                    respond_to do |format|
                        format.js { render :new_monster }
                    end

                else
                    @debrief.user_id = nil
                    @withname = false
                    respond_to do |format|
                        format.js { render :new_monster }
                    end
                end
            end
        end
        
        def create_player
            @debrief.player_debrief = true
            if params[:user_selected] == "true" and params[:character_selected] == "true"
                if @debrief.save
                    update_game_display
                else
                    respond_to do |format|
                        format.js { render :new_player }
                    end
                end
            elsif params[:user_selected] == "true"
                if @debrief.valid?
                    respond_to do |format|
                        format.js { render :new_player }
                    end
                else
                    @debrief.character_id = nil
                    respond_to do |format|
                        format.js { render :new_player }
                    end
                end
            else
                if @debrief.valid?
                    respond_to do |format|
                        format.js { render :new_player }
                    end
                else
                    @debrief.user_id = nil
                    respond_to do |format|
                        format.js { render :new_player }
                    end
                end
            end
        end
        
        def update_gm
            if @debrief.update(debrief_monster_params)
                update_game_display
            else
                respond_to do |format|
                    format.js { render :edit_gm}
                end
            end
        end
        
        def update_monster
            if @debrief.update(debrief_monster_params)
                update_game_display
            else
                respond_to do |format|
                    format.js { render :edit_monster }
                end
            end
        end
        
        def update_player
            @debrief.player_debrief = true
            if @debrief.update(debrief_player_params)
                update_game_display
            else
                respond_to do |format|
                    format.js { render :edit_player }
                end
            end
        end
        
        def update_game_display
            render :update_game
        end
        
        def unknown_debrief_type
            render :update do |page|
                flash[:error] = "Unknown debrief type."
                page.redirect_to games_path
            end
        end
end

app/helpers/debriefs_helper.rb
module DebriefsHelper
end

app/views/debriefs/_gm.html.erb
<%= form_with model: [@game, @debrief], local: false do |f| %>
    <%= f.error_messages :header_message => "Failed to save debrief", :message => "The following problems prevented the debrief from being saved:" %>
    
    <%= hidden_field_tag :debrief_type, "GM" %>
    
    <% if @debrief.user.nil? %>
        <%= hidden_field_tag :user_selected, "false" %>
        <ul class="form">
            <li>
                <%= f.label :user_id, "Select User, or #{link_to 'Create New User', new_gm_new_game_user_path(@game), method: :get, remote: true}".html_safe %>
                <%= f.collection_select :user_id, 
                                        User.order(:name).select{ |user| (user.deleted_at.nil? && (user.is_normal? || user.is_recent?)) && !@game.is_gm?(user) && !@game.monster_debriefs.any? { |debrief| debrief.user == user } },
                                        :id, :name, {}, id: :debrief_user_id %>
            </li>
        </ul>
    <% else %>
        <%= hidden_field_tag :user_selected, "true" %>
        <%= f.hidden_field :user_id %>
        <ul class="form">
            <li>
                <%= f.label :base_points, "Base Points (if different to Monster Base)" %>
                <%= f.number_field :base_points, id: :debrief_base_points %>
            </li>
            <li>
                <%= f.label :points_modifier, "GM Points" %>
                <%= f.number_field :points_modifier, id: :debrief_points_modifier %>
            </li>
            <li>
                <%= f.label :remarks, "Comments" %>
                <%= f.text_area :remarks, id: :debrief_remarks %>
            </li>
        </ul>
    <% end %>
<% end %>

app/views/debriefs/_monster.html.erb
<%= form_with model: [@game, @debrief], local: false do |f| %>
    <%= f.error_messages :header_message => "Failed to save debrief", :message => "The following problems prevented the debrief from being saved:" %>
    
    <%= hidden_field_tag :debrief_type, "Monster" %>
    
    <% if @debrief.user.nil? %>
        <%= hidden_field_tag :user_selected, "false" %>
        <ul class="form">
            <li>
                <%= f.label :user_id, "Select User, or #{link_to 'Create New User', new_monster_new_game_user_path(@game), :method => :get, :remote => true}".html_safe %>
                <%= f.collection_select :user_id, 
                                        User.order(:name).select{ |user| (user.deleted_at.nil? && (user.is_normal? || user.is_recent?)) and !@game.is_gm? user and !@game.monster_debriefs.any? { |debrief| debrief.user == user } },
                                        :id, :name, {}, id: :debrief_user_id %>
            </li>
        </ul>
    <% else %>
        <%= hidden_field_tag :user_selected, "true" %>
        <%= f.hidden_field :user_id %>
        <ul class="form">
            <li>
                <%= f.label :base_points, "Base Points (if different to Monster Base)" %>
                <%= f.number_field :base_points, id: :debrief_base_points %>
            </li>
            <li>
                <%= f.label :points_modifier, "Bonus Points" %>
                <%= f.number_field :points_modifier, id: :debrief_points_modifier %>
            </li>
            <li>
                <%= f.label :remarks, "Comments" %>
                <%= f.text_area :remarks, id: :debrief_remarks %>
            </li>
        </ul>
    <% end %>
<% end %>

app/views/debriefs/_player.html.erb
<%= form_with model: [@game, @debrief], local: false do |f| %>
    <%= f.error_messages :header_message => "Failed to save debrief", :message => "The following problems prevented the debrief from being saved:" %>
    
    <%= hidden_field_tag :debrief_type, "Player" %>
    
    <% if @debrief.user.nil? %>
        <%= hidden_field_tag :user_selected, "false" %>
        <%= hidden_field_tag :character_selected, "false" %>
        <ul class="form">
            <li>
                <%= f.label :user_id, "Select User, or #{link_to 'Create New User', new_player_new_game_user_path(@game), :method => :get, :remote => true}".html_safe %>
                <%= f.collection_select :user_id, 
                                        User.order(:name).select{ |user| (user.deleted_at.nil? && (user.is_normal? || user.is_recent?)) },
                                        :id, :name, {}, id: :debrief_user_id %>
            </li>
        </ul>
    <% elsif @debrief.character.nil? %>
        <%= hidden_field_tag :user_selected, "false" %>
        <%= hidden_field_tag :character_selected, "true" %>
        <%= f.hidden_field :user_id %>
        <ul class="form">
            <li>
                <%= f.label :character_id, "Select Character, or #{link_to 'Create New Character', new_player_new_game_user_character_path(@game, @debrief.user), :method => :get, :remote => true}".html_safe %>
                <%= f.collection_select :character_id, 
                                        @debrief.user.characters.order(:name).reject{ |character| @game.player_debriefs.any? {|debrief| debrief.character == character } },
                                        :id, :name_and_title, {}, id: :debrief_character_id %>
            </li>
        </ul>
    <% else %>
        <%= hidden_field_tag :user_selected, "true" %>
        <%= hidden_field_tag :character_selected, "true" %>
        <%= f.hidden_field :user_id %>
        <%= f.hidden_field :character_id %>
        <ul class="form">
            <li>
                <%= f.label :base_points, "Base Points (if different to Player Base)" %>
                <%= f.number_field :base_points, id: :debrief_base_points %>
            </li>
            <li>
                <%= f.label :deaths, "Deaths" %>
                <%= f.number_field :deaths, id: :debrief_deaths %>
            </li>
            <li>
                <%= f.label :points_modifier, "Bonus Points" %>
                <%= f.number_field :points_modifier, id: :debrief_points_modifier %>
            </li>
            <li>
                <%= f.label :money_modifier, "Pay Adjustment" %>
                <%= f.number_field :money_modifier, id: :debrief_money_modifier %>
            </li>
            <li>
                <%= f.label :loot, "Loot/Fines" %>
                <%= f.number_field :loot, id: :debrief_loot %>
            </li>
            <li>
                <%= f.label :remarks, "Comments" %>
                <%= f.text_area :remarks, id: :debrief_remarks %>
            </li>
            <%= f.fields_for :character do |cf| %>
            	<%= cf.hidden_field :id %>
            <li>
                <%= cf.label :gm_notes, "GM Notes" %>
                <%= cf.text_area :gm_notes, id: :debrief_character_attributes_gm_notes %>
            </li>
            <% end %>
        </ul>
    <% end %>
<% end %>

app/views/debriefs/edit_gm.js.erb
<%= render_dialog "debriefs/gm", "Edit GM - #{@debrief.user.display_name(current_user)}", "Update", "update" %>

app/views/debriefs/edit_monster.js.erb
<%= render_dialog "debriefs/monster", "Edit Monster - #{@debrief.user.display_name(current_user)}", "Update", "update" %>

app/views/debriefs/edit_player.js.erb
<%= render_dialog "debriefs/player", "Edit Player - #{@debrief.user.display_name(current_user)}", "Update", "update" %>

app/views/debriefs/new_gm.js.erb
<% if @withname %>
	<%= render_dialog "debriefs/gm", "Add GM - #{@debrief.user.display_name(current_user)}", "Select", "create" %>
<% else %>
	<%= render_dialog "debriefs/gm", "Add GM", "Select", "create" %>
<% end %>

app/views/debriefs/new_monster.js.erb
<% if @withname %>
	<%= render_dialog "debriefs/monster", "Add Monster - #{@debrief.user.display_name(current_user)}", "Select", "create" %>
<% else %>
	<%= render_dialog "debriefs/monster", "Add Monster", "Select", "create" %>
<% end %>

app/views/debriefs/new_player.js.erb
<% if @debrief.character.nil? %>
	<%= render_dialog "debriefs/player", "Add Player", "Select", "create" %>
<% else %>
	<%= render_dialog "debriefs/player", "Add Character - #{@debrief.character.name_and_title}", "Select", "create" %>
<% end %>

app/views/debriefs/update_game.js.erb
if ($("#dialog").hasClass('ui-dialog-content')) {
  $("#dialog").dialog("close");
}
$("#gamesummaryrow<%= @game.id %>").html('<%= j render :partial => "games/game_summary", :locals => { :game => @game, :shown => true } %>');
$("#gamedetailsrow<%= @game.id %>").html('<%= j render :partial => "games/game_detail", :locals => { :game => @game } %>');
$("#gamedetailsshow<%= @game.id %>").html('<%= j render :partial => "games/game", :locals => { :game => @game } %>');
updateShowDetailsActions("gamedetailsrow<%= @game.id %>", "show_details_<%= @game.id %>", "hide_details_<%= @game.id %>");