config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :acceptables

  devise_for :users, :controllers => { :sessions => "sessions", :registrations => "registrations" }

  resources :guild_memberships

  resources :messages, :except => [ :index, :show ] do
    member do
      patch     :undelete
      delete  :purge
      get     :move
      patch     :save_move
    end
  end

  resources :boards do
    member do
      patch :move_up
      patch :move_down
      patch :switch_open_or_closed
    end

    collection do
      get :admin
      get :mark_read
    end
  end

  resources :transactions, except: [:destroy]
  resources :campaigns

  resources :games do
    member do
      get :edit_ic_brief
      get :edit_ooc_brief
      get :edit_ic_debrief
      get :edit_ooc_debrief
      patch :update_ic_brief
      patch :update_ooc_brief
      patch :update_ic_debrief
      patch :update_ooc_debrief
      get :start_debrief
      patch :confirm_start_debrief
      patch :finish_debrief
      patch :reopen_debrief
      patch :publish_briefs
      get :first_aid_report
    end

    collection do
      get :outstanding_debriefs
    end

    resources :game_attendances, :except => [ :index, :show, :destroy ] do
      member do
        patch :clear_confirm_state
        patch :confirm
        patch :prioritise
        patch :reject
      end
    end

    resources :game_applications, :except => [ :show ] do
      member do
        get :approve_app
        get :reject_app
        patch :approve
        patch :reject
      end
    end

    resources :debriefs, :except => [ :show, :new, :edit, :index ] do
      new do
        get :new_gm
        get :new_player
        get :new_monster
      end

      member do
        get :edit_gm
        get :edit_player
        get :edit_monster
      end
    end

    resources :users, :except => [ :new, :create, :show, :edit, :update, :index, :destroy ] do
      new do
        get :new_gm
        get :new_player
        get :new_monster
        patch :create_gm
        patch :create_player
        patch :create_monster
      end

      resources :characters, :except => [ :new, :create, :show, :edit, :update, :index, :destroy ] do
        new do
          get :new_player
          patch :create_player
        end
      end
    end

    resource :gm_contact, :except => [ :show, :edit, :update, :index, :destroy ]

  end

  resources :characters do
    collection do
      get :show_all
    end

    member do
      get :edit_name
      get :edit_bio
      get :edit_date_of_birth
      get :edit_notes
      get :edit_player_notes
      get :edit_gm_notes
      get :edit_address
      patch :update_name
      patch :update_bio
      patch :update_date_of_birth
      patch :update_notes
      patch :update_player_notes
      patch :update_gm_notes
      patch :update_address
      patch :reactivate
      patch :retire
      patch :perm_kill
      patch :resurrect
      patch :approve
      patch :reject
      get :edit_rejected
      patch :update_rejected
      get :declare
      patch :save_declaration
      patch :recycle
    end

    resources :death_threshold_adjustments, :except => [ :index, :show, :destroy ] do
      member do
        patch :approve
        patch :reject
        patch :approve_from_approvals
        patch :reject_from_approvals
      end
    end
    resources :character_point_adjustments, :except => [ :index, :show, :destroy ] do
      member do
        patch :approve
        patch :reject
      end
    end

    resources :monster_point_spends, :except => [ :index, :show, :destroy, :edit, :update ] do
      new do
        delete :delete
      end
    end

    resources :guild_memberships, :except => [ :index, :show ] do
      new do
        post :leave
        post :eject
        post :eject_from_approvals
        get  :branch_change
        post :create_guild_branch_change
        post :make_full
        post :make_full_from_approvals
      end

      member do
        patch :approve
        patch :provisionally_approve
        patch :reject
        patch :approve_from_approvals
        patch :provisionally_approve_from_approvals
        patch :reject_from_approvals
      end
    end

    resources :transactions, :only => [ :new, :create, :destroy ] do
      new do
        get :new_to_character
      end
    end
  end

  resource :sidebar, :only => :edit do
    resources :sidebar_categories, :as => :categories do
      member do
        patch :move_up
        patch :move_down
      end
    end
    resources :sidebar_entries, :as => :entries do
      member do
        patch :move_up
        patch :move_down
      end
    end
  end

  resources :pages do
    member do
      get :home
    end
  end

  resources :users, :except => [ :edit, :update ] do
    collection do
      get  :merge_select_users
      post :merge_select_data
      post :merge
    end

    member do
      patch :suspend
      patch :unsuspend
      delete :purge
      patch :approve
      patch :undelete
      post :resend_activation
      get :monster_points
      get :edit_user_name
      patch :update_user_name
      get :edit_login
      patch :update_login
      get :edit_email
      patch :update_email
      get :edit_mobile_number
      patch :update_mobile_number
      get :edit_emergency_details
      patch :update_emergency_details
      get :edit_general_notes
      patch :update_general_notes
      patch :enable
      get :terms_and_conditions
      post :accept_terms_and_conditions
      post :reject_terms_and_conditions
      post :reject_terms_and_conditions_and_accept_suspension
    end

    resources :monster_point_adjustments, :except => [ :index, :show, :destroy ] do
      member do
        patch :approve
        patch :reject
        patch :approve_from_approvals
        patch :reject_from_approvals
      end
    end

    resource :monster_point_declaration, :except => [ :show, :destroy ] do
      member do
        patch :approve
        patch :reject
        patch :approve_from_approvals
        patch :reject_from_approvals
      end
    end

    resource  :account
    resources :roles, :only => [:index] do
      collection do
        post :update
      end
    end
  end

  resource :committee_contact, :except => [ :show, :edit, :update, :index, :destroy ]

  root :to => "pages#home"

  get "/event_calendar"   => "games#list_future",        :as => :event_calendar
  get "/past_games/:year" => "games#index",              :as => :past_games
  get "/next_game"        => "games#next_game",          :as => :next_game
  get "/my_characters"    => "characters#my_characters", :as => :my_characters
  get "/monster_points"   => "my_info#monster_points",   :as => :monster_points
  get "/approvals"        => "admin#approvals",          :as => :approvals
  get "/user_profile"     => "users#profile",            :as => :user_profile

  if Rails.env.production?
    get '404', :to => 'application#page_not_found'
    get '422', :to => 'application#server_error'
    get '500', :to => 'application#server_error'
  end
  
end

app/views/admin/approvals.html.erb
<h1 class="alt">Character Ref Approval Requests</h1>

<% if @character_requests.length > 0 %>
    <h2 class="alt">Character Requests</h2>
    <table class="prestyled">
        <thead>
            <tr>
                <th>Player</th>
                <th>Name</th>
                <th>Race</th>
                <th>Guild</th>
                <th class="numeric">Rank</th>
                <th class="numeric">Death Thresholds</th>
                <th class="actions">State</th>
            </tr>
        </thead>
        
        <tbody>
            <% @character_requests.each do |character| %>
                <tr class="<%= cycle('odd', 'even') %>">
                    <td><%=h character.user.name %></td>
                    <td>
                        <%= link_to character do %>
                            <%=h character.name_and_title %>
                        <% end %>
                    </td>
                    <td><%=h character.race.name %></td>
                    <td><%=h character.full_guild_name %></td>
                    <td class="numeric"><%=h character.rank %></td>
                    <td class="numeric"><%=h character.death_thresholds %></td>
                    <td class="actions"><%=h character.state_readable %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
<% end %>

<% reset_cycle %>

<% if @provisional_guild_memberships.length > 0 %>
    <h2 class="alt">Provisional Guild Memberships</h2>
    <table class="prestyled">
        <thead>
            <tr>
                <th>Player</th>
                <th>Character</th>
                <th>Guild</th>
                <th class="numeric">Games Played in Guild</th>
                <th class="numeric">Points Earned in Guild</th>
                <th class="actions">Actions</th>
            </tr>
        </thead>
        
        <tbody>
            <% @provisional_guild_memberships.each do |membership| %>
                <tr class="<%= cycle('odd', 'even') %>">
                    <td><%=h membership.character.user.name %></td>
                    <td><%=link_to membership.character.name, membership.character %></td>
                    <td><%=h membership.full_guild_name %></td>
                    <td class="numeric"><%= membership.character.games_played_since(membership.declared_on) %></td>
                    <td class="numeric"><%= membership.character.points_earned_since(membership.declared_on) %></td>
                    <td class="actions">
                        [ <%= link_to "Make full member", make_full_new_character_guild_membership_path(membership.character), :method => :post, :remote => true  %> ]<br/>
                        [ <%= link_to "Eject from guild", eject_new_character_guild_membership_path(membership.character), :method => :post, :remote => true %> ]
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
<% end %>

<% reset_cycle %>

<% if @guild_change_requests.length > 0 %>
    <h2 class="alt">Guild Change Requests</h2>
    <table class="prestyled">
        <thead>
            <tr>
                <th>Player</th>
                <th>Character</th>
                <th>Current Guild</th>
                <th>New Guild</th>
                <th class="actions">Actions</th>
            </tr>
        </thead>
        
        <tbody>
            <% @guild_change_requests.each do |request| %>
                <tr class="<%= cycle('odd', 'even') %>">
                    <td><%=h request.character.user.name %></td>
                    <td><%=link_to request.character.name, request.character %></td>
                    <td>
                        <% if request.character.full_guild_name != request.full_guild_name %>
                            <%=h request.character.full_guild_name %>
                        <% end %>
                    </td>
                    <td><%=h request.full_guild_name %></td>
                    <td class="actions">
                        [ <%= link_to "Approve guild change", approve_character_guild_membership_path(request.character, request), :method => :patch, :remote => true %> ]<br/>
                        [ <%= link_to "Approve as provisional guild member", provisionally_approve_character_guild_membership_path(request.character, request), :method => :patch, :remote => true %> ]<br/>
                        [ <%= link_to "Reject guild change", reject_character_guild_membership_path(request.character, request), :method => :patch, :remote => true %> ]
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
<% end %>

<% reset_cycle %>

<% if @character_point_adjustments.length > 0 %>
    <h2 class="alt">Character Point Adjustment Requests</h2>
    <table class="prestyled">
        <thead>
            <tr>
                <th>Player</th>
                <th>Character</th>
                <th>Date</th>
                <th>Reason</th>
                <th class="numeric">Adjustment</th>
                <th class="actions">Actions</th>
            </tr>
        </thead>
        
        <tbody>
            <% @character_point_adjustments.each do |adjustment| %>
                <tr class="character_point_adjustment <%= cycle('odd', 'even') %>">
                    <td><%=h adjustment.character.user.name %></td>
                    <td>
                        <%= link_to adjustment.character do %>
                            <%=h adjustment.character.name_and_title %>
                        <% end %>
                    </td>
                    <td><%=h adjustment.declared_on %></td>
                    <td><%=h adjustment.reason %></td>
                    <td class="numeric"><%= (adjustment.points >= 0 ? "+" : "") %><%=h adjustment.points %></td>
                    <td class="actions">
                        [ <%= link_to "Approve", approve_character_character_point_adjustment_path(adjustment.character, adjustment), :method => :patch, :remote => true %> ]<br/>
                        [ <%= link_to "Reject", reject_character_character_point_adjustment_path(adjustment.character, adjustment), :method => :patch, :remote => true %> ] 
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
<% end %>

<% reset_cycle %>

<% if @monster_point_declarations.length > 0 %>
    <h2 class="alt">Monster Point Declarations</h2>
    <table class="prestyled">
        <thead>
            <tr>
                <th>Player</th>
                <th>Date</th>
                <th class="numeric">Points</th>
                <th class="actions">Actions</th>
            </tr>
        </thead>
        
        <tbody>
            <% @monster_point_declarations.each do |declaration| %>
                <tr class="<%= cycle('odd', 'even') %>">
                    <td><%=link_to declaration.user.name, monster_points_user_path(declaration.user) %></td>
                    <td><%=h declaration.declared_on %></td>
                    <td class="numeric"><%=h declaration.points %></td>
                    <td class="actions">
                        [ <%= link_to "Approve", approve_user_monster_point_declaration_path(declaration.user), :method => :patch, :remote => true %> ]<br/>
                        [ <%= link_to "Reject", reject_user_monster_point_declaration_path(declaration.user), :method => :patch, :remote => true %> ]
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
<% end %>

<% reset_cycle %>

<% if @monster_point_adjustments.length > 0 %>
    <h2 class="alt">Monster Point Adjustment Requests</h2>
    <table class="prestyled">
        <thead>
            <tr>
                <th>Player</th>
                <th>Date</th>
                <th>Reason</th>
                <th class="numeric">Adjustment</th>
                <th class="actions">Actions</th>
            </tr>
        </thead>
        
        <tbody>
            <% @monster_point_adjustments.each do |adjustment| %>
                <tr class="<%= cycle('odd', 'even') %>">
                    <td><%=link_to adjustment.user.name, monster_points_user_path(adjustment.user) %></td>
                    <td><%=h adjustment.declared_on %></td>
                    <td><%=h adjustment.reason %></td>
                    <td class="numeric"><%= (adjustment.points >= 0 ? "+" : "") %><%=h adjustment.points %></td>
                    <td class="actions">
                        [ <%= link_to "Approve", approve_user_monster_point_adjustment_path(adjustment.user, adjustment), :method => :patch, :remote => true %> ]<br/> 
                        [ <%= link_to "Reject", reject_user_monster_point_adjustment_path(adjustment.user, adjustment), :method => :patch, :remote => true %> ]
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
<% end %>

<% reset_cycle %>

<% if @death_threshold_adjustments.length > 0 %>
    <h2 class="alt">Death Threshold Adjustment Requests</h2>
    <table class="prestyled">
        <thead>
            <tr>
                <th>Player</th>
                <th>Character</th>
                <th>Date</th>
                <th>Reason</th>
                <th class="numeric">Adjustment</th>
                <th class="actions">Actions</th>
            </tr>
        </thead>
        
        <tbody>
            <% @death_threshold_adjustments.each do |adjustment| %>
                <tr class="<%= cycle('odd', 'even') %>">
                    <td><%=h adjustment.character.user.name %></td>
                    <td>
                        <%= link_to adjustment.character do %>
                            <%=h adjustment.character.name_and_title %>
                        <% end %>
                    </td>
                    <td><%=h adjustment.declared_on %></td>
                    <td><%=h adjustment.reason %></td>
                    <td class="numeric"><%= (adjustment.change >= 0 ? "+" : "") %><%=h adjustment.change %></td>
                    <td class="actions">
                        [ <%= link_to "Approve", approve_character_death_threshold_adjustment_path(adjustment.character, adjustment), :method => :patch, :remote => true %> ]<br/> 
                        [ <%= link_to "Reject", reject_character_death_threshold_adjustment_path(adjustment.character, adjustment), :method => :patch, :remote => true %> ]
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
<% end %>