config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :acceptables

  devise_for :users, :controllers => { :sessions => "sessions", :registrations => "registrations" }

  resources :guild_memberships

  resources :messages, :except => [ :index, :show ] do
    member do
      patch     :undelete
      delete  :purge
      get     :move
      patch     :save_move
    end
  end

  resources :boards do
    member do
      patch :move_up
      patch :move_down
      patch :switch_open_or_closed
    end

    collection do
      get :admin
      get :mark_read
    end
  end

  resources :transactions, except: [:destroy]
  resources :campaigns

  resources :games do
    member do
      get :edit_ic_brief
      get :edit_ooc_brief
      get :edit_ic_debrief
      get :edit_ooc_debrief
      patch :update_ic_brief
      patch :update_ooc_brief
      patch :update_ic_debrief
      patch :update_ooc_debrief
      get :start_debrief
      patch :confirm_start_debrief
      patch :finish_debrief
      patch :reopen_debrief
      patch :publish_briefs
      get :first_aid_report
    end

    collection do
      get :outstanding_debriefs
    end

    resources :game_attendances, :except => [ :index, :show, :destroy ] do
      member do
        patch :clear_confirm_state
        patch :confirm
        patch :prioritise
        patch :reject
      end
    end

    resources :game_applications, :except => [ :show ] do
      member do
        get :approve_app
        get :reject_app
        patch :approve
        patch :reject
      end
    end

    resources :debriefs, :except => [ :show, :new, :edit, :index ] do
      new do
        get :new_gm
        get :new_player
        get :new_monster
      end

      member do
        get :edit_gm
        get :edit_player
        get :edit_monster
      end
    end

    resources :users, :except => [ :new, :create, :show, :edit, :update, :index, :destroy ] do
      new do
        get :new_gm
        get :new_player
        get :new_monster
        patch :create_gm
        patch :create_player
        patch :create_monster
      end

      resources :characters, :except => [ :new, :create, :show, :edit, :update, :index, :destroy ] do
        new do
          get :new_player
          patch :create_player
        end
      end
    end

    resource :gm_contact, :except => [ :show, :edit, :update, :index, :destroy ]

  end

  resources :characters do
    collection do
      get :show_all
    end

    member do
      get :edit_name
      get :edit_bio
      get :edit_date_of_birth
      get :edit_notes
      get :edit_player_notes
      get :edit_gm_notes
      get :edit_address
      patch :update_name
      patch :update_bio
      patch :update_date_of_birth
      patch :update_notes
      patch :update_player_notes
      patch :update_gm_notes
      patch :update_address
      patch :reactivate
      patch :retire
      patch :perm_kill
      patch :resurrect
      patch :approve
      patch :reject
      get :edit_rejected
      patch :update_rejected
      get :declare
      patch :save_declaration
      patch :recycle
    end

    resources :death_threshold_adjustments, :except => [ :index, :show, :destroy ] do
      member do
        patch :approve
        patch :reject
        patch :approve_from_approvals
        patch :reject_from_approvals
      end
    end
    resources :character_point_adjustments, :except => [ :index, :show, :destroy ] do
      member do
        patch :approve
        patch :reject
      end
    end

    resources :monster_point_spends, :except => [ :index, :show, :destroy, :edit, :update ] do
      new do
        delete :delete
      end
    end

    resources :guild_memberships, :except => [ :index, :show ] do
      new do
        post :leave
        post :eject
        post :eject_from_approvals
        get  :branch_change
        post :create_guild_branch_change
        post :make_full
        post :make_full_from_approvals
      end

      member do
        patch :approve
        patch :provisionally_approve
        patch :reject
        patch :approve_from_approvals
        patch :provisionally_approve_from_approvals
        patch :reject_from_approvals
      end
    end

    resources :transactions, :only => [ :new, :create, :destroy ] do
      new do
        get :new_to_character
      end
    end
  end

  resource :sidebar, :only => :edit do
    resources :sidebar_categories, :as => :categories do
      member do
        patch :move_up
        patch :move_down
      end
    end
    resources :sidebar_entries, :as => :entries do
      member do
        patch :move_up
        patch :move_down
      end
    end
  end

  resources :pages do
    member do
      get :home
    end
  end

  resources :users, :except => [ :edit, :update ] do
    collection do
      get  :merge_select_users
      post :merge_select_data
      post :merge
    end

    member do
      patch :suspend
      patch :unsuspend
      delete :purge
      patch :approve
      patch :undelete
      post :resend_activation
      get :monster_points
      get :edit_user_name
      patch :update_user_name
      get :edit_login
      patch :update_login
      get :edit_email
      patch :update_email
      get :edit_mobile_number
      patch :update_mobile_number
      get :edit_emergency_details
      patch :update_emergency_details
      get :edit_general_notes
      patch :update_general_notes
      patch :enable
      get :terms_and_conditions
      post :accept_terms_and_conditions
      post :reject_terms_and_conditions
      post :reject_terms_and_conditions_and_accept_suspension
    end

    resources :monster_point_adjustments, :except => [ :index, :show, :destroy ] do
      member do
        patch :approve
        patch :reject
        patch :approve_from_approvals
        patch :reject_from_approvals
      end
    end

    resource :monster_point_declaration, :except => [ :show, :destroy ] do
      member do
        patch :approve
        patch :reject
        patch :approve_from_approvals
        patch :reject_from_approvals
      end
    end

    resource  :account
    resources :roles, :only => [:index] do
      collection do
        post :update
      end
    end
  end

  resource :committee_contact, :except => [ :show, :edit, :update, :index, :destroy ]

  root :to => "pages#home"

  get "/event_calendar"   => "games#list_future",        :as => :event_calendar
  get "/past_games/:year" => "games#index",              :as => :past_games
  get "/next_game"        => "games#next_game",          :as => :next_game
  get "/my_characters"    => "characters#my_characters", :as => :my_characters
  get "/monster_points"   => "my_info#monster_points",   :as => :monster_points
  get "/approvals"        => "admin#approvals",          :as => :approvals
  get "/user_profile"     => "users#profile",            :as => :user_profile

  if Rails.env.production?
    get '404', :to => 'application#page_not_found'
    get '422', :to => 'application#server_error'
    get '500', :to => 'application#server_error'
  end
  
end

app/views/shared/_admin_notifications.html.erb
<% if current_user and (current_user.is_admin? or current_user.is_committee?) %>
	<% pending_users = User.where(state: Character::Active, approved_at: nil, deleted_at: nil).count %>
    <% if pending_users > 0 %>
        <p>
            There <%= ( pending_users == 1 ? "is" : "are" ) %> <%= pending_users %> user<%= "s" unless pending_users == 1 %> 
            <%= link_to "awaiting approval", users_path %>.
        </p>
    <% end %>
<% end %>
<% if current_user and current_user.has_outstanding_debriefs? %>
    <p>
        You have <%= link_to "games awaiting debrief", outstanding_debriefs_games_path %>.
    </p>
<% end %>
<% if current_user and current_user.is_character_ref? %>
    <%
    	pending_characters = Character.pending_characters(current_user).count
    	pending_guild_changes = GuildMembership.pending_guild_memberships(current_user).count
    	provisional_guild_memberships = GuildMembership.provisional_guild_memberships(current_user).count
		pending_cp_adjustments = CharacterPointAdjustment.pending_adjustments(current_user).count
		pending_mp_declarations = MonsterPointDeclaration.pending_declarations(current_user).count
    	pending_mp_adjustments = MonsterPointAdjustment.pending_adjustments(current_user).count
    	pending_dt_adjustments = DeathThresholdAdjustment.pending_adjustments(current_user).count
    %>
    <% if pending_characters + pending_guild_changes + provisional_guild_memberships + pending_cp_adjustments + pending_mp_declarations + pending_mp_adjustments + pending_dt_adjustments > 0 %>
        <p>Awaiting <%= link_to "approval", approvals_path %>:</p>
        <ul>
            <% if pending_characters > 0 %>
                <li><%= pending_characters %> character<%= "s" unless pending_characters == 1 %></li>
            <% end %>
            <% if pending_guild_changes > 0 %>
                <li><%= pending_guild_changes %> guild change<%= "s" unless pending_guild_changes == 1 %></li>
            <% end %>
            <% if provisional_guild_memberships > 0 %>
                <li><%= provisional_guild_memberships %> provisional guild membership<%= "s" unless provisional_guild_memberships == 1 %></li>
            <% end %>
            <% if pending_cp_adjustments > 0 %>
                <li><%= pending_cp_adjustments %> character point adjustment<%= "s" unless pending_cp_adjustments == 1 %></li>
            <% end %>
            <% if pending_mp_declarations > 0 %>
                <li><%= pending_mp_declarations %> monster point declaration<%= "s" unless pending_mp_declarations == 1 %></li>
            <% end %>
            <% if pending_mp_adjustments > 0 %>
                <li><%= pending_mp_adjustments %> monster point adjustment<%= "s" unless pending_mp_adjustments == 1 %></li>
            <% end %>
            <% if pending_dt_adjustments > 0 %>
                <li><%= pending_dt_adjustments %> death threshold adjustment<%= "s" unless pending_dt_adjustments == 1 %></li>
            <% end %>
        </ul>
    <% end %>
<% end %>
<% if current_user and current_user.is_committee? %>
    <% if pending_game_apps > 0 %>
        <p>
            There <%= ( pending_game_apps == 1 ? "is" : "are" ) %> <%= pending_game_apps %> game<%= "s" unless pending_game_apps == 1 %> 
            <%= link_to "with pending applications", event_calendar_path %>.
        </p>
    <% end %>
<% end %>
<% if current_user and current_user.needs_medical_update? %>
    <p>
        Your medical details <%= link_to "need updating", edit_emergency_details_user_path(current_user), :method => :get, :remote => true %>.
    </p>
<% end %>

app/views/shared/_dialog.html.erb
<% fields ||= [] %>
<div class="top_right_shadow">
    <div class="bottom_left_shadow">
        <div class="shadow">
            <div class="dialog_frame">
                <div class="dialog_header_bar">
                    <div class="dialog_title">
                        &nbsp;<%=h title %>
                    </div>

                    <div class="close_icon">
                        <%= link_to_function image_tag("close.png", :border => 0, :size => "12x12" ), "$('dialog').fade(); $('fader').fade(); return false;" %>
                    </div>
                </div>

                <div class="dialog_contents">
                    <%= render :partial => partial, :locals => { :action => action, :fields => fields } %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/shared/_sessionpanel.html.erb
<div id="sessionpanel">
    <div class="container non-printing">
        <div class="row">
            <% if user_signed_in? %>
                <span class="nobr">Logged in as <%=h current_user.username %></span> 
                &bull;
                <span class="nobr"><span id="current_monster_points"><%=h current_user.monster_points %></span> monster points</span>
                &bull;
                <span class="nobr">P:M ratio is <%=h current_user.games_played %>:<%=h current_user.games_monstered %></span>
                &bull;
                <% unread_messages = Board.total_unread_messages(current_user) %>
                <span class="nobr"><%= unread_messages %> <%= link_to "unread message#{unread_messages == 1 ? '' : 's'}", boards_path %>
                &bull;
                <span class="nobr"><%= link_to 'Log out', destroy_user_session_path, method: :delete %></span>
                <%= hidden_field_tag "logged_in", true %>
            <% else %>
                <span class="nobr">Not logged in</span> 
                &bull;
                <span class="nobr"><%= link_to 'Login', new_user_session_path %></span>
                &bull;
                <span class="nobr"><%= link_to "Register", new_user_registration_path %></span>
                <%= hidden_field_tag "logged_in", false %>
            <% end %> 
        </div>
    </div>
</div>